/* C program to dump the interupt vecters to disk
it will generate a report file called intvect.txt
July 24, 1995
getints.c */

#include "stdio.h"
#include "int.h"

typedef struct {
unsigned int seg;
unsigned int offset;
} seg_off;

main()
{
FILE *outfile;
int loop;
seg_off interrup[256];
for (loop=0;loop<=255;loop++)
int_getvector((unsigned)loop,&interrup[loop].seg,&interrup[loop].offset);
outfile=fopen("intvect.txt","w");
fprintf(outfile,"Interrupt Vector Report-Generated by getints.exe\n");
for (loop=0;loop<=127;loop++)
fprintf(outfile,"Int: %02X---Segment:%04X  Offset:%04X   Int: %02X---Segment:%04X  Offset:%04X\n",loop,interrup[loop].seg,interrup[loop].offset,loop+128,interrup[loop+128].seg,interrup[loop+128].offset);
}
